#!/bin/sh
#
# Runs before git flow feature finish
#
# Positional arguments:
# $1    The friendly name of the branch
# $2    The origin remote
# $3    The full branch name (including the feature prefix)
#
NAME=$1
ORIGIN=$2
BRANCH=$3

try{
	$ "C:\home\git-hook-entityframework\EntityFrameworkMigrationsFeatureFinish_CheckAllMigrationsRan.ps1"
}
catch(){
	# To terminate the git-flow action, return a non-zero exit code.
	exit 1;
}

#Clean up
exit 0